name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = false

[[kv_namespaces]]
binding = "SIREN"
id = "3fb31cc7e4fa4fbca7935ef536861eba"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "2d4c200c-21bf-11f0-9aaf-6f37010b8baf"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/SonzaiEkkusu/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/sub.html"
